Partial Support for flags

diff --git a/pakka b/pakka
--- a/pakka
+++ b/pakka
@@ -1,22 +1,21 @@
 #!/usr/bin/env bash
-# what the hell there's no comments???
-# pakka - simple aur helper
-set -eEu # what the hell is that?
-set -o pipefail # another crappy useless command???
-IFS=$'\n\t' # please remove those commands
-SELF=pakka
+# pakka - An AUR/custom helper for Arch Linux
+set -eEu
+set -o pipefail
+IFS=$'\n\t'
+SELF=Pakka
 SELF_PROG=$0
+CWD=$(pwd)
 
 CONFIGDIR=${CONFIGDIR:-$HOME/.config/pakka}
-# well, we need to tell the user, where config file doesn't exists
-if [ ! -f "$CONFIGDIR/config" ]; then
+# When the config file doesn't exists, exit.
+if [[ ! -f "$CONFIGDIR/config" ]]; then
 	echo "$SELF: Cannot load config file. Exiting"
 	exit 1
 fi
-. "$CONFIGDIR/config" # dot is much simplier than source and it's limited to bash and kornshell
-# CWD=$(pwd) # this is't needed as after script will exit, shell will go back to dir where script was started
 
-mkdir -p "$CACHEDIR/archive"
+. "$CONFIGDIR/config"
+
 mkdir -p "$CACHEDIR/packaging"
 mkdir -p "$CACHEDIR/packages"
 
@@ -40,57 +39,84 @@ exitm() {
     exit "$1"
 }
 
+flags_process() {
+    ARG1="$1"
+    [[ "$ARG1" == *"--sync"* ]] || [[ "$ARG1" == *!(-)"-S"* ]] && SYNC=true
+    [[ "$ARG1" == *"--search"* ]] || [[ "$ARG1" == *!(-)"-s"* ]] && SEARCH=true
+    [[ "$ARG1" == *"--update"* ]] || [[ "$ARG1" == *!(-)"-u"* ]] && UPDATE=true
+    echo 
+}
+
+update() {
+exit
+}
+
+refresh() {
+exit
+}
+
+search() {
+    exit
+}
 
 install() {
-    i="$1"
+    i="$1" # package name
     msg_info "Building $i"
-    SRCDIR=$CACHEDIR/packaging/$i
-    if [ ! -f "$CACHEDIR/archive/$i.tar.gz" ]; then
-        curl -L -o "$CACHEDIR/archive/$i.tar.gz" "https://aur.archlinux.org/cgit/aur.git/snapshot/$i.tar.gz"
+    SRCDIR="$CACHEDIR/packaging/$i"
+    # fetching the AUR Source
+    if [[ ! -d "$CACHEDIR/packaging/$i" ]]; then
+        git clone --depth=1 https://aur.archlinux.org/$i.git "$CACHEDIR/packaging/$i" || msg_error "Cannot download PKGBUILD"
+        cd "$SRCDIR"
+    else
+        cd "$SRCDIR"
+        git reset --hard
+        git pull
     fi
-    tar xzf "$CACHEDIR/archive/$i.tar.gz" -C "$CACHEDIR/packaging"
-    cd "$SRCDIR"
-    echo -n "$SELF: Wanna see PKGBUILD? [y/n] "
+    echo -n "${SELF}? Wanna see PKGBUILD? [y/n] "
     read q1
-    if [ "$q1" == "y" ]; then
+    if [[ "$q1" == "y" ]]; then
     	less PKGBUILD
     fi
-    echo -n "$SELF: Start building ${i}? [y/n] "
+    echo -n "${SELF}? Start building ${i}? [y/n] "
     read prompt
-    if [ ! "$prompt" == "y" ]; then
-    	msg_error Interrupted!
+    if [[ ! "$prompt" == "y" ]]; then
+    	msg_error "Interrupted!"
     fi
-    if [ -d "$CONFIGDIR/overrides/$i/srcpatch" ];
+    # Override: srcpatch
+    if [[ -d "$CONFIGDIR/overrides/$i/srcpatch" ]];
     then
         msg_info "Patching"
         for j in "$(ls $CONFIGDIR/overrides/$i/srcpatch/)";
         do
 	    patch -p1 < "$CONFIGDIR/overrides/$i/srcpatch/$j"
-	        msg_info "Patched $j !" || {
-                    echo -n "$SELF: Failed to patch. Ignore it and continue? [y/n] "
-		    read prompt2
-                    if [ ! "$prompt2" == "y" ]; then
-		    	msg_error Interrupted
-		    fi
-                }
+	    msg_info "Patched $j !" || {
+                echo -n "$SELF: Failed to patch. Ignore it and continue? [y/n] "
+		read prompt2
+                if [[ ! "$prompt2" == "y" ]]; then
+		    msg_error Interrupted
+		fi
+            }
         done
     fi
 
-    
-    if [ -d $"CONFIGDIR/overrides/$i/srccopy" ];
+    # Override: srccopy
+    if [[ -d "$CONFIGDIR/overrides/$i/srccopy" ]];
     then
-	cp -rv "$CONFIGDIR/overrides/$i/srccopy/*" "$SRCDIR" # i don't know why everything is doing so useless code parts. every path sould be double quoted
+	cp -rv "$CONFIGDIR/overrides/$i/srccopy/"* "$SRCDIR"
     fi
+    # Downloading sources
     makepkg -o
-    if [ -d "$CONFIGDIR/overrides/$i/copy" ];
+    # Override: copy
+    if [[ -d "$CONFIGDIR/overrides/$i/copy" ]];
     then
-	cp -rv "$CONFIGDIR/overrides/$i/copy/*" "$SRCDIR/src" # again...
+	cp -rv "$CONFIGDIR/overrides/$i/copy/"* "$SRCDIR/src"
     fi
     cd src/
-    if [ -d "$CONFIGDIR/overrides/$i/patch" ];
+    # Override: patch
+    if [[ -d "$CONFIGDIR/overrides/$i/patch" ]];
     then
         msg_info "Patching"
-        for j in "$(ls $CONFIGDIR/overrides/$i/patch/)" #; # agaaaaain
+        for j in "$(ls $CONFIGDIR/overrides/$i/patch/)"
         do
 	    patch < "$CONFIGDIR/overrides/$i/patch/$j" &&
 	        msg_info "Patched $j !" || {
@@ -100,25 +126,48 @@ install() {
         done
     fi
     cd ..
+    # Build Package
     makepkg -sci || {
-	read -rp "$SELF: Do you want to disable verify checks? [y/n] " prompt
-	if [[ $prompt == "y" ]];
-	then
+    if [[ "$?" == "1" ]]; then
+        read -rp "Do you want to disable verify checks? ${SELF}? [y/n] " prompt
+        if [[ $prompt == "y" ]];
+        then
 	    makepkg -sci --skipinteg;
-	fi
+        fi
+    fi
     }
 }
-
+PACKAGES=""
 ARGS=$*
 if [[ -z $ARGS ]]
 then
+    
+    pacman -Syu
     for i in $(cat "$CONFIGDIR/Packages");
     do
 	install $i
     done
 else
+    FLAGS=""
+    PACKAGES=""
     for i in $ARGS;
     do
-	install $i;
+        [[ $(echo $i | cut -c 1) == "-" ]] && FLAGS+="${i}" || PACKAGES+="$i "
+
     done
+    # parsing flags
+    SYNC=false
+    SEARCH=false
+    UPDATE=false
+    [[ -z $FLAGS ]] && FLAGS="-S"
+    echo $FLAGS
+    flags_process $FLAGS
+    echo $SYNC $SEARCH $UPDATE
+    if $SYNC;
+    then
+        for i in "$(echo $PACKAGES | sed 's/ /\n/g')";
+        do
+            install $i
+        done
+    fi
 fi
